### ISSUE TITLE
onboarding grafana

### ISSUE THREAD

**Issue by jaustinford** [jaustinford/ansible-es-labs#18]
**tasks**
- [x] onboard grafana server
  - [x] update dns zone files with server fqdn `grafana-prod.labs.elysianskies.com` dns records
  - [x] spin up vm
  - [x] manually set up user austin with authorized_keys
  - [x] set up `/etc/sudoers.d/austin`
  - [x] add to ansible inventory
  - [x] `make yumrepo`
  - [x] `make update`
  - [x] `make users`
  - [x] `make firewall`
  - [x] `make centos`
  - [x] `make nagios`
  - [x] update known_hosts public key in `make vars`
  - [x] reboot
- [x] ansible coding
  - [x] write grafana server role
  - [x] write playbook to point to role
  - [x] add playbook to Makefile
  - [x] add [/etc/nginx/conf.d/ssl.conf](https://github.com/jaustinford/ansible-es-labs/blob/master/es/roles/nginx/templates/etc/nginx/conf.d/ssl.conf) grafana route
