### ISSUE TITLE
onboard elk stack

### ISSUE THREAD

**Issue by jaustinford** [jaustinford/ansible-es-labs#26]
## task
- onboard ELK stack to replace syslog collector

## steps
- [ ] decommission `syslog-prod.labs.elysianskies.com`
- [ ] set up `elk-prod.labs.elysianskies.com`
  - [ ] `make vm_init group=elk-prod.labs.elysianskies.com`
  - [ ] automate elk tasks to install and configure ELK services
  - [ ] automate install for `filebeat` service on all clients
  - [ ] appropriate [firewall](https://github.com/jaustinford/ansible-es-labs/blob/master/es/roles/firewalld/templates/etc/firewalld/zones/public.xml) rules
  - [ ] testing

**Comment by jaustinford** [comment]
Project's blocked until this can be investigated. Original build said nothing of missing conf files in `/etc/logstash/conf.d/*.conf`. Kibana, logstash, and elasticsearch are cycling service restarts because of it.

```
[2019-07-21T18:22:23,064][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.2.0"}
[2019-07-21T18:22:24,064][INFO ][logstash.config.source.local.configpathloader] No config files found in path {:path=>"/etc/logstash/conf.d/*.conf"}
[2019-07-21T18:22:24,076][ERROR][logstash.config.sourceloader] No configuration found in the configured sources.
[2019-07-21T18:22:24,427][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2019-07-21T18:22:29,345][INFO ][logstash.runner          ] Logstash shut down.
```
